/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package br.org.stela.intelectus.lattes.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-6-9")
public class Pessoa implements org.apache.thrift.TBase<Pessoa, Pessoa._Fields>, java.io.Serializable, Cloneable, Comparable<Pessoa> {
	private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Pessoa");

	private static final org.apache.thrift.protocol.TField NRO_ID_CNPQ_FIELD_DESC =
			new org.apache.thrift.protocol.TField("nroIdCnpq", org.apache.thrift.protocol.TType.STRING, (short) 1);
	private static final org.apache.thrift.protocol.TField NME_RH_FIELD_DESC =
			new org.apache.thrift.protocol.TField("nmeRh", org.apache.thrift.protocol.TType.STRING, (short) 2);
	private static final org.apache.thrift.protocol.TField NME_CITACAO_BIBLIOG_FIELD_DESC =
			new org.apache.thrift.protocol.TField("nmeCitacaoBibliog", org.apache.thrift.protocol.TType.STRING, (short) 3);
	private static final org.apache.thrift.protocol.TField DTA_ATUALIZACAO_CURRICULO_FIELD_DESC =
			new org.apache.thrift.protocol.TField("dtaAtualizacaoCurriculo", org.apache.thrift.protocol.TType.I64, (short) 4);
	private static final org.apache.thrift.protocol.TField TPO_ENDER_CORR_FIELD_DESC =
			new org.apache.thrift.protocol.TField("tpoEnderCorr", org.apache.thrift.protocol.TType.STRING, (short) 5);
	private static final org.apache.thrift.protocol.TField DSC_COMENTARIO_FIELD_DESC =
			new org.apache.thrift.protocol.TField("dscComentario", org.apache.thrift.protocol.TType.STRING, (short) 6);
	private static final org.apache.thrift.protocol.TField ENDERECOS_FIELD_DESC =
			new org.apache.thrift.protocol.TField("enderecos", org.apache.thrift.protocol.TType.LIST, (short) 7);
	private static final org.apache.thrift.protocol.TField FORMACOES_FIELD_DESC =
			new org.apache.thrift.protocol.TField("formacoes", org.apache.thrift.protocol.TType.LIST, (short) 8);
	private static final org.apache.thrift.protocol.TField ATUACOES_FIELD_DESC =
			new org.apache.thrift.protocol.TField("atuacoes", org.apache.thrift.protocol.TType.LIST, (short) 9);
	private static final org.apache.thrift.protocol.TField PRODUCOES_FIELD_DESC =
			new org.apache.thrift.protocol.TField("producoes", org.apache.thrift.protocol.TType.LIST, (short) 10);
	private static final org.apache.thrift.protocol.TField NATUREZA_PROJETOS_FIELD_DESC =
			new org.apache.thrift.protocol.TField("naturezaProjetos", org.apache.thrift.protocol.TType.LIST, (short) 11);
	private static final org.apache.thrift.protocol.TField PALAVRAS_CHAVE_FIELD_DESC =
			new org.apache.thrift.protocol.TField("palavrasChave", org.apache.thrift.protocol.TType.LIST, (short) 12);
	private static final org.apache.thrift.protocol.TField AREAS_ATUACAO_FIELD_DESC =
			new org.apache.thrift.protocol.TField("areasAtuacao", org.apache.thrift.protocol.TType.LIST, (short) 13);

	private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();

	static {
		schemes.put(StandardScheme.class, new PessoaStandardSchemeFactory());
		schemes.put(TupleScheme.class, new PessoaTupleSchemeFactory());
	}

	private String nroIdCnpq; // required
	private String nmeRh; // required
	private String nmeCitacaoBibliog; // optional
	private long dtaAtualizacaoCurriculo; // required
	private String tpoEnderCorr; // optional
	private String dscComentario; // optional
	private List<Endereco> enderecos; // optional
	private List<Formacao> formacoes; // optional
	private List<AtuacaoAtividade> atuacoes; // optional
	private List<Producao> producoes; // optional
	private List<NaturezaProjeto> naturezaProjetos; // optional
	private List<PalavraChave> palavrasChave; // optional
	private List<AreaAtuacao> areasAtuacao; // optional

	/** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
	public enum _Fields implements org.apache.thrift.TFieldIdEnum {
		NRO_ID_CNPQ((short) 1, "nroIdCnpq"),
		NME_RH((short) 2, "nmeRh"),
		NME_CITACAO_BIBLIOG((short) 3, "nmeCitacaoBibliog"),
		DTA_ATUALIZACAO_CURRICULO((short) 4, "dtaAtualizacaoCurriculo"),
		TPO_ENDER_CORR((short) 5, "tpoEnderCorr"),
		DSC_COMENTARIO((short) 6, "dscComentario"),
		ENDERECOS((short) 7, "enderecos"),
		FORMACOES((short) 8, "formacoes"),
		ATUACOES((short) 9, "atuacoes"),
		PRODUCOES((short) 10, "producoes"),
		NATUREZA_PROJETOS((short) 11, "naturezaProjetos"),
		PALAVRAS_CHAVE((short) 12, "palavrasChave"),
		AREAS_ATUACAO((short) 13, "areasAtuacao");

		private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

		static {
			for (_Fields field : EnumSet.allOf(_Fields.class)) {
				byName.put(field.getFieldName(), field);
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, or null if its not found.
		 */
		public static _Fields findByThriftId(int fieldId) {
			switch (fieldId) {
			case 1: // NRO_ID_CNPQ
				return NRO_ID_CNPQ;
			case 2: // NME_RH
				return NME_RH;
			case 3: // NME_CITACAO_BIBLIOG
				return NME_CITACAO_BIBLIOG;
			case 4: // DTA_ATUALIZACAO_CURRICULO
				return DTA_ATUALIZACAO_CURRICULO;
			case 5: // TPO_ENDER_CORR
				return TPO_ENDER_CORR;
			case 6: // DSC_COMENTARIO
				return DSC_COMENTARIO;
			case 7: // ENDERECOS
				return ENDERECOS;
			case 8: // FORMACOES
				return FORMACOES;
			case 9: // ATUACOES
				return ATUACOES;
			case 10: // PRODUCOES
				return PRODUCOES;
			case 11: // NATUREZA_PROJETOS
				return NATUREZA_PROJETOS;
			case 12: // PALAVRAS_CHAVE
				return PALAVRAS_CHAVE;
			case 13: // AREAS_ATUACAO
				return AREAS_ATUACAO;
			default:
				return null;
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, throwing an exception if it is not found.
		 */
		public static _Fields findByThriftIdOrThrow(int fieldId) {
			_Fields fields = findByThriftId(fieldId);
			if (fields == null)
				throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
			return fields;
		}

		/**
		 * Find the _Fields constant that matches name, or null if its not found.
		 */
		public static _Fields findByName(String name) {
			return byName.get(name);
		}

		private final short _thriftId;
		private final String _fieldName;

		_Fields(short thriftId, String fieldName) {
			_thriftId = thriftId;
			_fieldName = fieldName;
		}

		public short getThriftFieldId() {
			return _thriftId;
		}

		public String getFieldName() {
			return _fieldName;
		}
	}

	// isset id assignments
	private static final int __DTAATUALIZACAOCURRICULO_ISSET_ID = 0;
	private byte __isset_bitfield = 0;
	private static final _Fields optionals[] = {_Fields.NME_CITACAO_BIBLIOG, _Fields.TPO_ENDER_CORR, _Fields.DSC_COMENTARIO, _Fields.ENDERECOS,
			_Fields.FORMACOES, _Fields.ATUACOES, _Fields.PRODUCOES, _Fields.NATUREZA_PROJETOS, _Fields.PALAVRAS_CHAVE, _Fields.AREAS_ATUACAO};
	public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

	static {
		Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
		tmpMap.put(_Fields.NRO_ID_CNPQ, new org.apache.thrift.meta_data.FieldMetaData("nroIdCnpq", org.apache.thrift.TFieldRequirementType.REQUIRED,
				new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
		tmpMap.put(_Fields.NME_RH, new org.apache.thrift.meta_data.FieldMetaData("nmeRh", org.apache.thrift.TFieldRequirementType.REQUIRED,
				new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
		tmpMap.put(_Fields.NME_CITACAO_BIBLIOG, new org.apache.thrift.meta_data.FieldMetaData("nmeCitacaoBibliog",
				org.apache.thrift.TFieldRequirementType.OPTIONAL, new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
		tmpMap.put(_Fields.DTA_ATUALIZACAO_CURRICULO,
				new org.apache.thrift.meta_data.FieldMetaData("dtaAtualizacaoCurriculo", org.apache.thrift.TFieldRequirementType.REQUIRED,
						new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64, "timestamp")));
		tmpMap.put(_Fields.TPO_ENDER_CORR, new org.apache.thrift.meta_data.FieldMetaData("tpoEnderCorr", org.apache.thrift.TFieldRequirementType.OPTIONAL,
				new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
		tmpMap.put(_Fields.DSC_COMENTARIO, new org.apache.thrift.meta_data.FieldMetaData("dscComentario", org.apache.thrift.TFieldRequirementType.OPTIONAL,
				new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
		tmpMap.put(_Fields.ENDERECOS,
				new org.apache.thrift.meta_data.FieldMetaData("enderecos", org.apache.thrift.TFieldRequirementType.OPTIONAL,
						new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
								new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Endereco.class))));
		tmpMap.put(_Fields.FORMACOES,
				new org.apache.thrift.meta_data.FieldMetaData("formacoes", org.apache.thrift.TFieldRequirementType.OPTIONAL,
						new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
								new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Formacao.class))));
		tmpMap.put(_Fields.ATUACOES,
				new org.apache.thrift.meta_data.FieldMetaData("atuacoes", org.apache.thrift.TFieldRequirementType.OPTIONAL,
						new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
								new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AtuacaoAtividade.class))));
		tmpMap.put(_Fields.PRODUCOES,
				new org.apache.thrift.meta_data.FieldMetaData("producoes", org.apache.thrift.TFieldRequirementType.OPTIONAL,
						new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
								new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Producao.class))));
		tmpMap.put(_Fields.NATUREZA_PROJETOS,
				new org.apache.thrift.meta_data.FieldMetaData("naturezaProjetos", org.apache.thrift.TFieldRequirementType.OPTIONAL,
						new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
								new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, NaturezaProjeto.class))));
		tmpMap.put(_Fields.PALAVRAS_CHAVE,
				new org.apache.thrift.meta_data.FieldMetaData("palavrasChave", org.apache.thrift.TFieldRequirementType.OPTIONAL,
						new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
								new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PalavraChave.class))));
		tmpMap.put(_Fields.AREAS_ATUACAO,
				new org.apache.thrift.meta_data.FieldMetaData("areasAtuacao", org.apache.thrift.TFieldRequirementType.OPTIONAL,
						new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
								new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AreaAtuacao.class))));
		metaDataMap = Collections.unmodifiableMap(tmpMap);
		org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Pessoa.class, metaDataMap);
	}

	public Pessoa() {
	}

	public Pessoa(String nroIdCnpq, String nmeRh, long dtaAtualizacaoCurriculo) {
		this();
		this.nroIdCnpq = nroIdCnpq;
		this.nmeRh = nmeRh;
		this.dtaAtualizacaoCurriculo = dtaAtualizacaoCurriculo;
		setDtaAtualizacaoCurriculoIsSet(true);
	}

	/**
	 * Performs a deep copy on <i>other</i>.
	 */
	public Pessoa(Pessoa other) {
		__isset_bitfield = other.__isset_bitfield;
		if (other.isSetNroIdCnpq()) {
			this.nroIdCnpq = other.nroIdCnpq;
		}
		if (other.isSetNmeRh()) {
			this.nmeRh = other.nmeRh;
		}
		if (other.isSetNmeCitacaoBibliog()) {
			this.nmeCitacaoBibliog = other.nmeCitacaoBibliog;
		}
		this.dtaAtualizacaoCurriculo = other.dtaAtualizacaoCurriculo;
		if (other.isSetTpoEnderCorr()) {
			this.tpoEnderCorr = other.tpoEnderCorr;
		}
		if (other.isSetDscComentario()) {
			this.dscComentario = other.dscComentario;
		}
		if (other.isSetEnderecos()) {
			List<Endereco> __this__enderecos = new ArrayList<Endereco>(other.enderecos.size());
			for (Endereco other_element : other.enderecos) {
				__this__enderecos.add(new Endereco(other_element));
			}
			this.enderecos = __this__enderecos;
		}
		if (other.isSetFormacoes()) {
			List<Formacao> __this__formacoes = new ArrayList<Formacao>(other.formacoes.size());
			for (Formacao other_element : other.formacoes) {
				__this__formacoes.add(new Formacao(other_element));
			}
			this.formacoes = __this__formacoes;
		}
		if (other.isSetAtuacoes()) {
			List<AtuacaoAtividade> __this__atuacoes = new ArrayList<AtuacaoAtividade>(other.atuacoes.size());
			for (AtuacaoAtividade other_element : other.atuacoes) {
				__this__atuacoes.add(new AtuacaoAtividade(other_element));
			}
			this.atuacoes = __this__atuacoes;
		}
		if (other.isSetProducoes()) {
			List<Producao> __this__producoes = new ArrayList<Producao>(other.producoes.size());
			for (Producao other_element : other.producoes) {
				__this__producoes.add(new Producao(other_element));
			}
			this.producoes = __this__producoes;
		}
		if (other.isSetNaturezaProjetos()) {
			List<NaturezaProjeto> __this__naturezaProjetos = new ArrayList<NaturezaProjeto>(other.naturezaProjetos.size());
			for (NaturezaProjeto other_element : other.naturezaProjetos) {
				__this__naturezaProjetos.add(new NaturezaProjeto(other_element));
			}
			this.naturezaProjetos = __this__naturezaProjetos;
		}
		if (other.isSetPalavrasChave()) {
			List<PalavraChave> __this__palavrasChave = new ArrayList<PalavraChave>(other.palavrasChave.size());
			for (PalavraChave other_element : other.palavrasChave) {
				__this__palavrasChave.add(new PalavraChave(other_element));
			}
			this.palavrasChave = __this__palavrasChave;
		}
		if (other.isSetAreasAtuacao()) {
			List<AreaAtuacao> __this__areasAtuacao = new ArrayList<AreaAtuacao>(other.areasAtuacao.size());
			for (AreaAtuacao other_element : other.areasAtuacao) {
				__this__areasAtuacao.add(new AreaAtuacao(other_element));
			}
			this.areasAtuacao = __this__areasAtuacao;
		}
	}

	public Pessoa deepCopy() {
		return new Pessoa(this);
	}

	@Override
	public void clear() {
		this.nroIdCnpq = null;
		this.nmeRh = null;
		this.nmeCitacaoBibliog = null;
		setDtaAtualizacaoCurriculoIsSet(false);
		this.dtaAtualizacaoCurriculo = 0;
		this.tpoEnderCorr = null;
		this.dscComentario = null;
		this.enderecos = null;
		this.formacoes = null;
		this.atuacoes = null;
		this.producoes = null;
		this.naturezaProjetos = null;
		this.palavrasChave = null;
		this.areasAtuacao = null;
	}

	public String getNroIdCnpq() {
		return this.nroIdCnpq;
	}

	public void setNroIdCnpq(String nroIdCnpq) {
		this.nroIdCnpq = nroIdCnpq;
	}

	public void unsetNroIdCnpq() {
		this.nroIdCnpq = null;
	}

	/** Returns true if field nroIdCnpq is set (has been assigned a value) and false otherwise */
	public boolean isSetNroIdCnpq() {
		return this.nroIdCnpq != null;
	}

	public void setNroIdCnpqIsSet(boolean value) {
		if (!value) {
			this.nroIdCnpq = null;
		}
	}

	public String getNmeRh() {
		return this.nmeRh;
	}

	public void setNmeRh(String nmeRh) {
		this.nmeRh = nmeRh;
	}

	public void unsetNmeRh() {
		this.nmeRh = null;
	}

	/** Returns true if field nmeRh is set (has been assigned a value) and false otherwise */
	public boolean isSetNmeRh() {
		return this.nmeRh != null;
	}

	public void setNmeRhIsSet(boolean value) {
		if (!value) {
			this.nmeRh = null;
		}
	}

	public String getNmeCitacaoBibliog() {
		return this.nmeCitacaoBibliog;
	}

	public void setNmeCitacaoBibliog(String nmeCitacaoBibliog) {
		this.nmeCitacaoBibliog = nmeCitacaoBibliog;
	}

	public void unsetNmeCitacaoBibliog() {
		this.nmeCitacaoBibliog = null;
	}

	/** Returns true if field nmeCitacaoBibliog is set (has been assigned a value) and false otherwise */
	public boolean isSetNmeCitacaoBibliog() {
		return this.nmeCitacaoBibliog != null;
	}

	public void setNmeCitacaoBibliogIsSet(boolean value) {
		if (!value) {
			this.nmeCitacaoBibliog = null;
		}
	}

	public long getDtaAtualizacaoCurriculo() {
		return this.dtaAtualizacaoCurriculo;
	}

	public void setDtaAtualizacaoCurriculo(long dtaAtualizacaoCurriculo) {
		this.dtaAtualizacaoCurriculo = dtaAtualizacaoCurriculo;
		setDtaAtualizacaoCurriculoIsSet(true);
	}

	public void unsetDtaAtualizacaoCurriculo() {
		__isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __DTAATUALIZACAOCURRICULO_ISSET_ID);
	}

	/** Returns true if field dtaAtualizacaoCurriculo is set (has been assigned a value) and false otherwise */
	public boolean isSetDtaAtualizacaoCurriculo() {
		return EncodingUtils.testBit(__isset_bitfield, __DTAATUALIZACAOCURRICULO_ISSET_ID);
	}

	public void setDtaAtualizacaoCurriculoIsSet(boolean value) {
		__isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __DTAATUALIZACAOCURRICULO_ISSET_ID, value);
	}

	public String getTpoEnderCorr() {
		return this.tpoEnderCorr;
	}

	public void setTpoEnderCorr(String tpoEnderCorr) {
		this.tpoEnderCorr = tpoEnderCorr;
	}

	public void unsetTpoEnderCorr() {
		this.tpoEnderCorr = null;
	}

	/** Returns true if field tpoEnderCorr is set (has been assigned a value) and false otherwise */
	public boolean isSetTpoEnderCorr() {
		return this.tpoEnderCorr != null;
	}

	public void setTpoEnderCorrIsSet(boolean value) {
		if (!value) {
			this.tpoEnderCorr = null;
		}
	}

	public String getDscComentario() {
		return this.dscComentario;
	}

	public void setDscComentario(String dscComentario) {
		this.dscComentario = dscComentario;
	}

	public void unsetDscComentario() {
		this.dscComentario = null;
	}

	/** Returns true if field dscComentario is set (has been assigned a value) and false otherwise */
	public boolean isSetDscComentario() {
		return this.dscComentario != null;
	}

	public void setDscComentarioIsSet(boolean value) {
		if (!value) {
			this.dscComentario = null;
		}
	}

	public int getEnderecosSize() {
		return (this.enderecos == null) ? 0 : this.enderecos.size();
	}

	public java.util.Iterator<Endereco> getEnderecosIterator() {
		return (this.enderecos == null) ? null : this.enderecos.iterator();
	}

	public void addToEnderecos(Endereco elem) {
		if (this.enderecos == null) {
			this.enderecos = new ArrayList<Endereco>();
		}
		this.enderecos.add(elem);
	}

	public List<Endereco> getEnderecos() {
		return this.enderecos;
	}

	public void setEnderecos(List<Endereco> enderecos) {
		this.enderecos = enderecos;
	}

	public void unsetEnderecos() {
		this.enderecos = null;
	}

	/** Returns true if field enderecos is set (has been assigned a value) and false otherwise */
	public boolean isSetEnderecos() {
		return this.enderecos != null;
	}

	public void setEnderecosIsSet(boolean value) {
		if (!value) {
			this.enderecos = null;
		}
	}

	public int getFormacoesSize() {
		return (this.formacoes == null) ? 0 : this.formacoes.size();
	}

	public java.util.Iterator<Formacao> getFormacoesIterator() {
		return (this.formacoes == null) ? null : this.formacoes.iterator();
	}

	public void addToFormacoes(Formacao elem) {
		if (this.formacoes == null) {
			this.formacoes = new ArrayList<Formacao>();
		}
		this.formacoes.add(elem);
	}

	public List<Formacao> getFormacoes() {
		return this.formacoes;
	}

	public void setFormacoes(List<Formacao> formacoes) {
		this.formacoes = formacoes;
	}

	public void unsetFormacoes() {
		this.formacoes = null;
	}

	/** Returns true if field formacoes is set (has been assigned a value) and false otherwise */
	public boolean isSetFormacoes() {
		return this.formacoes != null;
	}

	public void setFormacoesIsSet(boolean value) {
		if (!value) {
			this.formacoes = null;
		}
	}

	public int getAtuacoesSize() {
		return (this.atuacoes == null) ? 0 : this.atuacoes.size();
	}

	public java.util.Iterator<AtuacaoAtividade> getAtuacoesIterator() {
		return (this.atuacoes == null) ? null : this.atuacoes.iterator();
	}

	public void addToAtuacoes(AtuacaoAtividade elem) {
		if (this.atuacoes == null) {
			this.atuacoes = new ArrayList<AtuacaoAtividade>();
		}
		this.atuacoes.add(elem);
	}

	public List<AtuacaoAtividade> getAtuacoes() {
		return this.atuacoes;
	}

	public void setAtuacoes(List<AtuacaoAtividade> atuacoes) {
		this.atuacoes = atuacoes;
	}

	public void unsetAtuacoes() {
		this.atuacoes = null;
	}

	/** Returns true if field atuacoes is set (has been assigned a value) and false otherwise */
	public boolean isSetAtuacoes() {
		return this.atuacoes != null;
	}

	public void setAtuacoesIsSet(boolean value) {
		if (!value) {
			this.atuacoes = null;
		}
	}

	public int getProducoesSize() {
		return (this.producoes == null) ? 0 : this.producoes.size();
	}

	public java.util.Iterator<Producao> getProducoesIterator() {
		return (this.producoes == null) ? null : this.producoes.iterator();
	}

	public void addToProducoes(Producao elem) {
		if (this.producoes == null) {
			this.producoes = new ArrayList<Producao>();
		}
		this.producoes.add(elem);
	}

	public List<Producao> getProducoes() {
		return this.producoes;
	}

	public void setProducoes(List<Producao> producoes) {
		this.producoes = producoes;
	}

	public void unsetProducoes() {
		this.producoes = null;
	}

	/** Returns true if field producoes is set (has been assigned a value) and false otherwise */
	public boolean isSetProducoes() {
		return this.producoes != null;
	}

	public void setProducoesIsSet(boolean value) {
		if (!value) {
			this.producoes = null;
		}
	}

	public int getNaturezaProjetosSize() {
		return (this.naturezaProjetos == null) ? 0 : this.naturezaProjetos.size();
	}

	public java.util.Iterator<NaturezaProjeto> getNaturezaProjetosIterator() {
		return (this.naturezaProjetos == null) ? null : this.naturezaProjetos.iterator();
	}

	public void addToNaturezaProjetos(NaturezaProjeto elem) {
		if (this.naturezaProjetos == null) {
			this.naturezaProjetos = new ArrayList<NaturezaProjeto>();
		}
		this.naturezaProjetos.add(elem);
	}

	public List<NaturezaProjeto> getNaturezaProjetos() {
		return this.naturezaProjetos;
	}

	public void setNaturezaProjetos(List<NaturezaProjeto> naturezaProjetos) {
		this.naturezaProjetos = naturezaProjetos;
	}

	public void unsetNaturezaProjetos() {
		this.naturezaProjetos = null;
	}

	/** Returns true if field naturezaProjetos is set (has been assigned a value) and false otherwise */
	public boolean isSetNaturezaProjetos() {
		return this.naturezaProjetos != null;
	}

	public void setNaturezaProjetosIsSet(boolean value) {
		if (!value) {
			this.naturezaProjetos = null;
		}
	}

	public int getPalavrasChaveSize() {
		return (this.palavrasChave == null) ? 0 : this.palavrasChave.size();
	}

	public java.util.Iterator<PalavraChave> getPalavrasChaveIterator() {
		return (this.palavrasChave == null) ? null : this.palavrasChave.iterator();
	}

	public void addToPalavrasChave(PalavraChave elem) {
		if (this.palavrasChave == null) {
			this.palavrasChave = new ArrayList<PalavraChave>();
		}
		this.palavrasChave.add(elem);
	}

	public List<PalavraChave> getPalavrasChave() {
		return this.palavrasChave;
	}

	public void setPalavrasChave(List<PalavraChave> palavrasChave) {
		this.palavrasChave = palavrasChave;
	}

	public void unsetPalavrasChave() {
		this.palavrasChave = null;
	}

	/** Returns true if field palavrasChave is set (has been assigned a value) and false otherwise */
	public boolean isSetPalavrasChave() {
		return this.palavrasChave != null;
	}

	public void setPalavrasChaveIsSet(boolean value) {
		if (!value) {
			this.palavrasChave = null;
		}
	}

	public int getAreasAtuacaoSize() {
		return (this.areasAtuacao == null) ? 0 : this.areasAtuacao.size();
	}

	public java.util.Iterator<AreaAtuacao> getAreasAtuacaoIterator() {
		return (this.areasAtuacao == null) ? null : this.areasAtuacao.iterator();
	}

	public void addToAreasAtuacao(AreaAtuacao elem) {
		if (this.areasAtuacao == null) {
			this.areasAtuacao = new ArrayList<AreaAtuacao>();
		}
		this.areasAtuacao.add(elem);
	}

	public List<AreaAtuacao> getAreasAtuacao() {
		return this.areasAtuacao;
	}

	public void setAreasAtuacao(List<AreaAtuacao> areasAtuacao) {
		this.areasAtuacao = areasAtuacao;
	}

	public void unsetAreasAtuacao() {
		this.areasAtuacao = null;
	}

	/** Returns true if field areasAtuacao is set (has been assigned a value) and false otherwise */
	public boolean isSetAreasAtuacao() {
		return this.areasAtuacao != null;
	}

	public void setAreasAtuacaoIsSet(boolean value) {
		if (!value) {
			this.areasAtuacao = null;
		}
	}

	public void setFieldValue(_Fields field, Object value) {
		switch (field) {
		case NRO_ID_CNPQ:
			if (value == null) {
				unsetNroIdCnpq();
			} else {
				setNroIdCnpq((String) value);
			}
			break;

		case NME_RH:
			if (value == null) {
				unsetNmeRh();
			} else {
				setNmeRh((String) value);
			}
			break;

		case NME_CITACAO_BIBLIOG:
			if (value == null) {
				unsetNmeCitacaoBibliog();
			} else {
				setNmeCitacaoBibliog((String) value);
			}
			break;

		case DTA_ATUALIZACAO_CURRICULO:
			if (value == null) {
				unsetDtaAtualizacaoCurriculo();
			} else {
				setDtaAtualizacaoCurriculo((Long) value);
			}
			break;

		case TPO_ENDER_CORR:
			if (value == null) {
				unsetTpoEnderCorr();
			} else {
				setTpoEnderCorr((String) value);
			}
			break;

		case DSC_COMENTARIO:
			if (value == null) {
				unsetDscComentario();
			} else {
				setDscComentario((String) value);
			}
			break;

		case ENDERECOS:
			if (value == null) {
				unsetEnderecos();
			} else {
				setEnderecos((List<Endereco>) value);
			}
			break;

		case FORMACOES:
			if (value == null) {
				unsetFormacoes();
			} else {
				setFormacoes((List<Formacao>) value);
			}
			break;

		case ATUACOES:
			if (value == null) {
				unsetAtuacoes();
			} else {
				setAtuacoes((List<AtuacaoAtividade>) value);
			}
			break;

		case PRODUCOES:
			if (value == null) {
				unsetProducoes();
			} else {
				setProducoes((List<Producao>) value);
			}
			break;

		case NATUREZA_PROJETOS:
			if (value == null) {
				unsetNaturezaProjetos();
			} else {
				setNaturezaProjetos((List<NaturezaProjeto>) value);
			}
			break;

		case PALAVRAS_CHAVE:
			if (value == null) {
				unsetPalavrasChave();
			} else {
				setPalavrasChave((List<PalavraChave>) value);
			}
			break;

		case AREAS_ATUACAO:
			if (value == null) {
				unsetAreasAtuacao();
			} else {
				setAreasAtuacao((List<AreaAtuacao>) value);
			}
			break;

		}
	}

	public Object getFieldValue(_Fields field) {
		switch (field) {
		case NRO_ID_CNPQ:
			return getNroIdCnpq();

		case NME_RH:
			return getNmeRh();

		case NME_CITACAO_BIBLIOG:
			return getNmeCitacaoBibliog();

		case DTA_ATUALIZACAO_CURRICULO:
			return Long.valueOf(getDtaAtualizacaoCurriculo());

		case TPO_ENDER_CORR:
			return getTpoEnderCorr();

		case DSC_COMENTARIO:
			return getDscComentario();

		case ENDERECOS:
			return getEnderecos();

		case FORMACOES:
			return getFormacoes();

		case ATUACOES:
			return getAtuacoes();

		case PRODUCOES:
			return getProducoes();

		case NATUREZA_PROJETOS:
			return getNaturezaProjetos();

		case PALAVRAS_CHAVE:
			return getPalavrasChave();

		case AREAS_ATUACAO:
			return getAreasAtuacao();

		}
		throw new IllegalStateException();
	}

	/** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
	public boolean isSet(_Fields field) {
		if (field == null) {
			throw new IllegalArgumentException();
		}

		switch (field) {
		case NRO_ID_CNPQ:
			return isSetNroIdCnpq();
		case NME_RH:
			return isSetNmeRh();
		case NME_CITACAO_BIBLIOG:
			return isSetNmeCitacaoBibliog();
		case DTA_ATUALIZACAO_CURRICULO:
			return isSetDtaAtualizacaoCurriculo();
		case TPO_ENDER_CORR:
			return isSetTpoEnderCorr();
		case DSC_COMENTARIO:
			return isSetDscComentario();
		case ENDERECOS:
			return isSetEnderecos();
		case FORMACOES:
			return isSetFormacoes();
		case ATUACOES:
			return isSetAtuacoes();
		case PRODUCOES:
			return isSetProducoes();
		case NATUREZA_PROJETOS:
			return isSetNaturezaProjetos();
		case PALAVRAS_CHAVE:
			return isSetPalavrasChave();
		case AREAS_ATUACAO:
			return isSetAreasAtuacao();
		}
		throw new IllegalStateException();
	}

	@Override
	public boolean equals(Object that) {
		if (that == null)
			return false;
		if (that instanceof Pessoa)
			return this.equals((Pessoa) that);
		return false;
	}

	public boolean equals(Pessoa that) {
		if (that == null)
			return false;

		boolean this_present_nroIdCnpq = true && this.isSetNroIdCnpq();
		boolean that_present_nroIdCnpq = true && that.isSetNroIdCnpq();
		if (this_present_nroIdCnpq || that_present_nroIdCnpq) {
			if (!(this_present_nroIdCnpq && that_present_nroIdCnpq))
				return false;
			if (!this.nroIdCnpq.equals(that.nroIdCnpq))
				return false;
		}

		boolean this_present_nmeRh = true && this.isSetNmeRh();
		boolean that_present_nmeRh = true && that.isSetNmeRh();
		if (this_present_nmeRh || that_present_nmeRh) {
			if (!(this_present_nmeRh && that_present_nmeRh))
				return false;
			if (!this.nmeRh.equals(that.nmeRh))
				return false;
		}

		boolean this_present_nmeCitacaoBibliog = true && this.isSetNmeCitacaoBibliog();
		boolean that_present_nmeCitacaoBibliog = true && that.isSetNmeCitacaoBibliog();
		if (this_present_nmeCitacaoBibliog || that_present_nmeCitacaoBibliog) {
			if (!(this_present_nmeCitacaoBibliog && that_present_nmeCitacaoBibliog))
				return false;
			if (!this.nmeCitacaoBibliog.equals(that.nmeCitacaoBibliog))
				return false;
		}

		boolean this_present_dtaAtualizacaoCurriculo = true;
		boolean that_present_dtaAtualizacaoCurriculo = true;
		if (this_present_dtaAtualizacaoCurriculo || that_present_dtaAtualizacaoCurriculo) {
			if (!(this_present_dtaAtualizacaoCurriculo && that_present_dtaAtualizacaoCurriculo))
				return false;
			if (this.dtaAtualizacaoCurriculo != that.dtaAtualizacaoCurriculo)
				return false;
		}

		boolean this_present_tpoEnderCorr = true && this.isSetTpoEnderCorr();
		boolean that_present_tpoEnderCorr = true && that.isSetTpoEnderCorr();
		if (this_present_tpoEnderCorr || that_present_tpoEnderCorr) {
			if (!(this_present_tpoEnderCorr && that_present_tpoEnderCorr))
				return false;
			if (!this.tpoEnderCorr.equals(that.tpoEnderCorr))
				return false;
		}

		boolean this_present_dscComentario = true && this.isSetDscComentario();
		boolean that_present_dscComentario = true && that.isSetDscComentario();
		if (this_present_dscComentario || that_present_dscComentario) {
			if (!(this_present_dscComentario && that_present_dscComentario))
				return false;
			if (!this.dscComentario.equals(that.dscComentario))
				return false;
		}

		boolean this_present_enderecos = true && this.isSetEnderecos();
		boolean that_present_enderecos = true && that.isSetEnderecos();
		if (this_present_enderecos || that_present_enderecos) {
			if (!(this_present_enderecos && that_present_enderecos))
				return false;
			if (!this.enderecos.equals(that.enderecos))
				return false;
		}

		boolean this_present_formacoes = true && this.isSetFormacoes();
		boolean that_present_formacoes = true && that.isSetFormacoes();
		if (this_present_formacoes || that_present_formacoes) {
			if (!(this_present_formacoes && that_present_formacoes))
				return false;
			if (!this.formacoes.equals(that.formacoes))
				return false;
		}

		boolean this_present_atuacoes = true && this.isSetAtuacoes();
		boolean that_present_atuacoes = true && that.isSetAtuacoes();
		if (this_present_atuacoes || that_present_atuacoes) {
			if (!(this_present_atuacoes && that_present_atuacoes))
				return false;
			if (!this.atuacoes.equals(that.atuacoes))
				return false;
		}

		boolean this_present_producoes = true && this.isSetProducoes();
		boolean that_present_producoes = true && that.isSetProducoes();
		if (this_present_producoes || that_present_producoes) {
			if (!(this_present_producoes && that_present_producoes))
				return false;
			if (!this.producoes.equals(that.producoes))
				return false;
		}

		boolean this_present_naturezaProjetos = true && this.isSetNaturezaProjetos();
		boolean that_present_naturezaProjetos = true && that.isSetNaturezaProjetos();
		if (this_present_naturezaProjetos || that_present_naturezaProjetos) {
			if (!(this_present_naturezaProjetos && that_present_naturezaProjetos))
				return false;
			if (!this.naturezaProjetos.equals(that.naturezaProjetos))
				return false;
		}

		boolean this_present_palavrasChave = true && this.isSetPalavrasChave();
		boolean that_present_palavrasChave = true && that.isSetPalavrasChave();
		if (this_present_palavrasChave || that_present_palavrasChave) {
			if (!(this_present_palavrasChave && that_present_palavrasChave))
				return false;
			if (!this.palavrasChave.equals(that.palavrasChave))
				return false;
		}

		boolean this_present_areasAtuacao = true && this.isSetAreasAtuacao();
		boolean that_present_areasAtuacao = true && that.isSetAreasAtuacao();
		if (this_present_areasAtuacao || that_present_areasAtuacao) {
			if (!(this_present_areasAtuacao && that_present_areasAtuacao))
				return false;
			if (!this.areasAtuacao.equals(that.areasAtuacao))
				return false;
		}

		return true;
	}

	@Override
	public int hashCode() {
		List<Object> list = new ArrayList<Object>();

		boolean present_nroIdCnpq = true && (isSetNroIdCnpq());
		list.add(present_nroIdCnpq);
		if (present_nroIdCnpq)
			list.add(nroIdCnpq);

		boolean present_nmeRh = true && (isSetNmeRh());
		list.add(present_nmeRh);
		if (present_nmeRh)
			list.add(nmeRh);

		boolean present_nmeCitacaoBibliog = true && (isSetNmeCitacaoBibliog());
		list.add(present_nmeCitacaoBibliog);
		if (present_nmeCitacaoBibliog)
			list.add(nmeCitacaoBibliog);

		boolean present_dtaAtualizacaoCurriculo = true;
		list.add(present_dtaAtualizacaoCurriculo);
		if (present_dtaAtualizacaoCurriculo)
			list.add(dtaAtualizacaoCurriculo);

		boolean present_tpoEnderCorr = true && (isSetTpoEnderCorr());
		list.add(present_tpoEnderCorr);
		if (present_tpoEnderCorr)
			list.add(tpoEnderCorr);

		boolean present_dscComentario = true && (isSetDscComentario());
		list.add(present_dscComentario);
		if (present_dscComentario)
			list.add(dscComentario);

		boolean present_enderecos = true && (isSetEnderecos());
		list.add(present_enderecos);
		if (present_enderecos)
			list.add(enderecos);

		boolean present_formacoes = true && (isSetFormacoes());
		list.add(present_formacoes);
		if (present_formacoes)
			list.add(formacoes);

		boolean present_atuacoes = true && (isSetAtuacoes());
		list.add(present_atuacoes);
		if (present_atuacoes)
			list.add(atuacoes);

		boolean present_producoes = true && (isSetProducoes());
		list.add(present_producoes);
		if (present_producoes)
			list.add(producoes);

		boolean present_naturezaProjetos = true && (isSetNaturezaProjetos());
		list.add(present_naturezaProjetos);
		if (present_naturezaProjetos)
			list.add(naturezaProjetos);

		boolean present_palavrasChave = true && (isSetPalavrasChave());
		list.add(present_palavrasChave);
		if (present_palavrasChave)
			list.add(palavrasChave);

		boolean present_areasAtuacao = true && (isSetAreasAtuacao());
		list.add(present_areasAtuacao);
		if (present_areasAtuacao)
			list.add(areasAtuacao);

		return list.hashCode();
	}

	@Override
	public int compareTo(Pessoa other) {
		if (!getClass().equals(other.getClass())) {
			return getClass().getName().compareTo(other.getClass().getName());
		}

		int lastComparison = 0;

		lastComparison = Boolean.valueOf(isSetNroIdCnpq()).compareTo(other.isSetNroIdCnpq());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetNroIdCnpq()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nroIdCnpq, other.nroIdCnpq);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetNmeRh()).compareTo(other.isSetNmeRh());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetNmeRh()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nmeRh, other.nmeRh);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetNmeCitacaoBibliog()).compareTo(other.isSetNmeCitacaoBibliog());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetNmeCitacaoBibliog()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nmeCitacaoBibliog, other.nmeCitacaoBibliog);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetDtaAtualizacaoCurriculo()).compareTo(other.isSetDtaAtualizacaoCurriculo());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetDtaAtualizacaoCurriculo()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dtaAtualizacaoCurriculo, other.dtaAtualizacaoCurriculo);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetTpoEnderCorr()).compareTo(other.isSetTpoEnderCorr());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetTpoEnderCorr()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tpoEnderCorr, other.tpoEnderCorr);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetDscComentario()).compareTo(other.isSetDscComentario());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetDscComentario()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dscComentario, other.dscComentario);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetEnderecos()).compareTo(other.isSetEnderecos());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetEnderecos()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.enderecos, other.enderecos);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetFormacoes()).compareTo(other.isSetFormacoes());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetFormacoes()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.formacoes, other.formacoes);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetAtuacoes()).compareTo(other.isSetAtuacoes());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetAtuacoes()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.atuacoes, other.atuacoes);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetProducoes()).compareTo(other.isSetProducoes());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetProducoes()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.producoes, other.producoes);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetNaturezaProjetos()).compareTo(other.isSetNaturezaProjetos());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetNaturezaProjetos()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.naturezaProjetos, other.naturezaProjetos);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetPalavrasChave()).compareTo(other.isSetPalavrasChave());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetPalavrasChave()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.palavrasChave, other.palavrasChave);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetAreasAtuacao()).compareTo(other.isSetAreasAtuacao());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetAreasAtuacao()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.areasAtuacao, other.areasAtuacao);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		return 0;
	}

	public _Fields fieldForId(int fieldId) {
		return _Fields.findByThriftId(fieldId);
	}

	public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
		schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
	}

	public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
		schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Pessoa(");
		boolean first = true;

		sb.append("nroIdCnpq:");
		if (this.nroIdCnpq == null) {
			sb.append("null");
		} else {
			sb.append(this.nroIdCnpq);
		}
		first = false;
		if (!first)
			sb.append(", ");
		sb.append("nmeRh:");
		if (this.nmeRh == null) {
			sb.append("null");
		} else {
			sb.append(this.nmeRh);
		}
		first = false;
		if (isSetNmeCitacaoBibliog()) {
			if (!first)
				sb.append(", ");
			sb.append("nmeCitacaoBibliog:");
			if (this.nmeCitacaoBibliog == null) {
				sb.append("null");
			} else {
				sb.append(this.nmeCitacaoBibliog);
			}
			first = false;
		}
		if (!first)
			sb.append(", ");
		sb.append("dtaAtualizacaoCurriculo:");
		sb.append(this.dtaAtualizacaoCurriculo);
		first = false;
		if (isSetTpoEnderCorr()) {
			if (!first)
				sb.append(", ");
			sb.append("tpoEnderCorr:");
			if (this.tpoEnderCorr == null) {
				sb.append("null");
			} else {
				sb.append(this.tpoEnderCorr);
			}
			first = false;
		}
		if (isSetDscComentario()) {
			if (!first)
				sb.append(", ");
			sb.append("dscComentario:");
			if (this.dscComentario == null) {
				sb.append("null");
			} else {
				sb.append(this.dscComentario);
			}
			first = false;
		}
		if (isSetEnderecos()) {
			if (!first)
				sb.append(", ");
			sb.append("enderecos:");
			if (this.enderecos == null) {
				sb.append("null");
			} else {
				sb.append(this.enderecos);
			}
			first = false;
		}
		if (isSetFormacoes()) {
			if (!first)
				sb.append(", ");
			sb.append("formacoes:");
			if (this.formacoes == null) {
				sb.append("null");
			} else {
				sb.append(this.formacoes);
			}
			first = false;
		}
		if (isSetAtuacoes()) {
			if (!first)
				sb.append(", ");
			sb.append("atuacoes:");
			if (this.atuacoes == null) {
				sb.append("null");
			} else {
				sb.append(this.atuacoes);
			}
			first = false;
		}
		if (isSetProducoes()) {
			if (!first)
				sb.append(", ");
			sb.append("producoes:");
			if (this.producoes == null) {
				sb.append("null");
			} else {
				sb.append(this.producoes);
			}
			first = false;
		}
		if (isSetNaturezaProjetos()) {
			if (!first)
				sb.append(", ");
			sb.append("naturezaProjetos:");
			if (this.naturezaProjetos == null) {
				sb.append("null");
			} else {
				sb.append(this.naturezaProjetos);
			}
			first = false;
		}
		if (isSetPalavrasChave()) {
			if (!first)
				sb.append(", ");
			sb.append("palavrasChave:");
			if (this.palavrasChave == null) {
				sb.append("null");
			} else {
				sb.append(this.palavrasChave);
			}
			first = false;
		}
		if (isSetAreasAtuacao()) {
			if (!first)
				sb.append(", ");
			sb.append("areasAtuacao:");
			if (this.areasAtuacao == null) {
				sb.append("null");
			} else {
				sb.append(this.areasAtuacao);
			}
			first = false;
		}
		sb.append(")");
		return sb.toString();
	}

	public void validate() throws org.apache.thrift.TException {
		// check for required fields
		if (!isSetNroIdCnpq()) {
			throw new org.apache.thrift.protocol.TProtocolException("Required field 'nroIdCnpq' is unset! Struct:" + toString());
		}

		if (!isSetNmeRh()) {
			throw new org.apache.thrift.protocol.TProtocolException("Required field 'nmeRh' is unset! Struct:" + toString());
		}

		if (!isSetDtaAtualizacaoCurriculo()) {
			throw new org.apache.thrift.protocol.TProtocolException("Required field 'dtaAtualizacaoCurriculo' is unset! Struct:" + toString());
		}

		// check for sub-struct validity
	}

	private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
		try {
			write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
		} catch (org.apache.thrift.TException te) {
			throw new java.io.IOException(te);
		}
	}

	private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
		try {
			// it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
			__isset_bitfield = 0;
			read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
		} catch (org.apache.thrift.TException te) {
			throw new java.io.IOException(te);
		}
	}

	private static class PessoaStandardSchemeFactory implements SchemeFactory {
		public PessoaStandardScheme getScheme() {
			return new PessoaStandardScheme();
		}
	}

	private static class PessoaStandardScheme extends StandardScheme<Pessoa> {

		public void read(org.apache.thrift.protocol.TProtocol iprot, Pessoa struct) throws org.apache.thrift.TException {
			org.apache.thrift.protocol.TField schemeField;
			iprot.readStructBegin();
			while (true) {
				schemeField = iprot.readFieldBegin();
				if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
					break;
				}
				switch (schemeField.id) {
				case 1: // NRO_ID_CNPQ
					if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
						struct.nroIdCnpq = iprot.readString();
						struct.setNroIdCnpqIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 2: // NME_RH
					if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
						struct.nmeRh = iprot.readString();
						struct.setNmeRhIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 3: // NME_CITACAO_BIBLIOG
					if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
						struct.nmeCitacaoBibliog = iprot.readString();
						struct.setNmeCitacaoBibliogIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 4: // DTA_ATUALIZACAO_CURRICULO
					if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
						struct.dtaAtualizacaoCurriculo = iprot.readI64();
						struct.setDtaAtualizacaoCurriculoIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 5: // TPO_ENDER_CORR
					if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
						struct.tpoEnderCorr = iprot.readString();
						struct.setTpoEnderCorrIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 6: // DSC_COMENTARIO
					if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
						struct.dscComentario = iprot.readString();
						struct.setDscComentarioIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 7: // ENDERECOS
					if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
						{
							org.apache.thrift.protocol.TList _list48 = iprot.readListBegin();
							struct.enderecos = new ArrayList<Endereco>(_list48.size);
							Endereco _elem49;
							for (int _i50 = 0; _i50 < _list48.size; ++_i50) {
								_elem49 = new Endereco();
								_elem49.read(iprot);
								struct.enderecos.add(_elem49);
							}
							iprot.readListEnd();
						}
						struct.setEnderecosIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 8: // FORMACOES
					if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
						{
							org.apache.thrift.protocol.TList _list51 = iprot.readListBegin();
							struct.formacoes = new ArrayList<Formacao>(_list51.size);
							Formacao _elem52;
							for (int _i53 = 0; _i53 < _list51.size; ++_i53) {
								_elem52 = new Formacao();
								_elem52.read(iprot);
								struct.formacoes.add(_elem52);
							}
							iprot.readListEnd();
						}
						struct.setFormacoesIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 9: // ATUACOES
					if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
						{
							org.apache.thrift.protocol.TList _list54 = iprot.readListBegin();
							struct.atuacoes = new ArrayList<AtuacaoAtividade>(_list54.size);
							AtuacaoAtividade _elem55;
							for (int _i56 = 0; _i56 < _list54.size; ++_i56) {
								_elem55 = new AtuacaoAtividade();
								_elem55.read(iprot);
								struct.atuacoes.add(_elem55);
							}
							iprot.readListEnd();
						}
						struct.setAtuacoesIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 10: // PRODUCOES
					if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
						{
							org.apache.thrift.protocol.TList _list57 = iprot.readListBegin();
							struct.producoes = new ArrayList<Producao>(_list57.size);
							Producao _elem58;
							for (int _i59 = 0; _i59 < _list57.size; ++_i59) {
								_elem58 = new Producao();
								_elem58.read(iprot);
								struct.producoes.add(_elem58);
							}
							iprot.readListEnd();
						}
						struct.setProducoesIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 11: // NATUREZA_PROJETOS
					if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
						{
							org.apache.thrift.protocol.TList _list60 = iprot.readListBegin();
							struct.naturezaProjetos = new ArrayList<NaturezaProjeto>(_list60.size);
							NaturezaProjeto _elem61;
							for (int _i62 = 0; _i62 < _list60.size; ++_i62) {
								_elem61 = new NaturezaProjeto();
								_elem61.read(iprot);
								struct.naturezaProjetos.add(_elem61);
							}
							iprot.readListEnd();
						}
						struct.setNaturezaProjetosIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 12: // PALAVRAS_CHAVE
					if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
						{
							org.apache.thrift.protocol.TList _list63 = iprot.readListBegin();
							struct.palavrasChave = new ArrayList<PalavraChave>(_list63.size);
							PalavraChave _elem64;
							for (int _i65 = 0; _i65 < _list63.size; ++_i65) {
								_elem64 = new PalavraChave();
								_elem64.read(iprot);
								struct.palavrasChave.add(_elem64);
							}
							iprot.readListEnd();
						}
						struct.setPalavrasChaveIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 13: // AREAS_ATUACAO
					if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
						{
							org.apache.thrift.protocol.TList _list66 = iprot.readListBegin();
							struct.areasAtuacao = new ArrayList<AreaAtuacao>(_list66.size);
							AreaAtuacao _elem67;
							for (int _i68 = 0; _i68 < _list66.size; ++_i68) {
								_elem67 = new AreaAtuacao();
								_elem67.read(iprot);
								struct.areasAtuacao.add(_elem67);
							}
							iprot.readListEnd();
						}
						struct.setAreasAtuacaoIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				default:
					org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
				}
				iprot.readFieldEnd();
			}
			iprot.readStructEnd();
			struct.validate();
		}

		public void write(org.apache.thrift.protocol.TProtocol oprot, Pessoa struct) throws org.apache.thrift.TException {
			struct.validate();

			oprot.writeStructBegin(STRUCT_DESC);
			if (struct.nroIdCnpq != null) {
				oprot.writeFieldBegin(NRO_ID_CNPQ_FIELD_DESC);
				oprot.writeString(struct.nroIdCnpq);
				oprot.writeFieldEnd();
			}
			if (struct.nmeRh != null) {
				oprot.writeFieldBegin(NME_RH_FIELD_DESC);
				oprot.writeString(struct.nmeRh);
				oprot.writeFieldEnd();
			}
			if (struct.nmeCitacaoBibliog != null) {
				if (struct.isSetNmeCitacaoBibliog()) {
					oprot.writeFieldBegin(NME_CITACAO_BIBLIOG_FIELD_DESC);
					oprot.writeString(struct.nmeCitacaoBibliog);
					oprot.writeFieldEnd();
				}
			}
			oprot.writeFieldBegin(DTA_ATUALIZACAO_CURRICULO_FIELD_DESC);
			oprot.writeI64(struct.dtaAtualizacaoCurriculo);
			oprot.writeFieldEnd();
			if (struct.tpoEnderCorr != null) {
				if (struct.isSetTpoEnderCorr()) {
					oprot.writeFieldBegin(TPO_ENDER_CORR_FIELD_DESC);
					oprot.writeString(struct.tpoEnderCorr);
					oprot.writeFieldEnd();
				}
			}
			if (struct.dscComentario != null) {
				if (struct.isSetDscComentario()) {
					oprot.writeFieldBegin(DSC_COMENTARIO_FIELD_DESC);
					oprot.writeString(struct.dscComentario);
					oprot.writeFieldEnd();
				}
			}
			if (struct.enderecos != null) {
				if (struct.isSetEnderecos()) {
					oprot.writeFieldBegin(ENDERECOS_FIELD_DESC);
					{
						oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.enderecos.size()));
						for (Endereco _iter69 : struct.enderecos) {
							_iter69.write(oprot);
						}
						oprot.writeListEnd();
					}
					oprot.writeFieldEnd();
				}
			}
			if (struct.formacoes != null) {
				if (struct.isSetFormacoes()) {
					oprot.writeFieldBegin(FORMACOES_FIELD_DESC);
					{
						oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.formacoes.size()));
						for (Formacao _iter70 : struct.formacoes) {
							_iter70.write(oprot);
						}
						oprot.writeListEnd();
					}
					oprot.writeFieldEnd();
				}
			}
			if (struct.atuacoes != null) {
				if (struct.isSetAtuacoes()) {
					oprot.writeFieldBegin(ATUACOES_FIELD_DESC);
					{
						oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.atuacoes.size()));
						for (AtuacaoAtividade _iter71 : struct.atuacoes) {
							_iter71.write(oprot);
						}
						oprot.writeListEnd();
					}
					oprot.writeFieldEnd();
				}
			}
			if (struct.producoes != null) {
				if (struct.isSetProducoes()) {
					oprot.writeFieldBegin(PRODUCOES_FIELD_DESC);
					{
						oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.producoes.size()));
						for (Producao _iter72 : struct.producoes) {
							_iter72.write(oprot);
						}
						oprot.writeListEnd();
					}
					oprot.writeFieldEnd();
				}
			}
			if (struct.naturezaProjetos != null) {
				if (struct.isSetNaturezaProjetos()) {
					oprot.writeFieldBegin(NATUREZA_PROJETOS_FIELD_DESC);
					{
						oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.naturezaProjetos.size()));
						for (NaturezaProjeto _iter73 : struct.naturezaProjetos) {
							_iter73.write(oprot);
						}
						oprot.writeListEnd();
					}
					oprot.writeFieldEnd();
				}
			}
			if (struct.palavrasChave != null) {
				if (struct.isSetPalavrasChave()) {
					oprot.writeFieldBegin(PALAVRAS_CHAVE_FIELD_DESC);
					{
						oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.palavrasChave.size()));
						for (PalavraChave _iter74 : struct.palavrasChave) {
							_iter74.write(oprot);
						}
						oprot.writeListEnd();
					}
					oprot.writeFieldEnd();
				}
			}
			if (struct.areasAtuacao != null) {
				if (struct.isSetAreasAtuacao()) {
					oprot.writeFieldBegin(AREAS_ATUACAO_FIELD_DESC);
					{
						oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.areasAtuacao.size()));
						for (AreaAtuacao _iter75 : struct.areasAtuacao) {
							_iter75.write(oprot);
						}
						oprot.writeListEnd();
					}
					oprot.writeFieldEnd();
				}
			}
			oprot.writeFieldStop();
			oprot.writeStructEnd();
		}

	}

	private static class PessoaTupleSchemeFactory implements SchemeFactory {
		public PessoaTupleScheme getScheme() {
			return new PessoaTupleScheme();
		}
	}

	private static class PessoaTupleScheme extends TupleScheme<Pessoa> {

		@Override
		public void write(org.apache.thrift.protocol.TProtocol prot, Pessoa struct) throws org.apache.thrift.TException {
			TTupleProtocol oprot = (TTupleProtocol) prot;
			oprot.writeString(struct.nroIdCnpq);
			oprot.writeString(struct.nmeRh);
			oprot.writeI64(struct.dtaAtualizacaoCurriculo);
			BitSet optionals = new BitSet();
			if (struct.isSetNmeCitacaoBibliog()) {
				optionals.set(0);
			}
			if (struct.isSetTpoEnderCorr()) {
				optionals.set(1);
			}
			if (struct.isSetDscComentario()) {
				optionals.set(2);
			}
			if (struct.isSetEnderecos()) {
				optionals.set(3);
			}
			if (struct.isSetFormacoes()) {
				optionals.set(4);
			}
			if (struct.isSetAtuacoes()) {
				optionals.set(5);
			}
			if (struct.isSetProducoes()) {
				optionals.set(6);
			}
			if (struct.isSetNaturezaProjetos()) {
				optionals.set(7);
			}
			if (struct.isSetPalavrasChave()) {
				optionals.set(8);
			}
			if (struct.isSetAreasAtuacao()) {
				optionals.set(9);
			}
			oprot.writeBitSet(optionals, 10);
			if (struct.isSetNmeCitacaoBibliog()) {
				oprot.writeString(struct.nmeCitacaoBibliog);
			}
			if (struct.isSetTpoEnderCorr()) {
				oprot.writeString(struct.tpoEnderCorr);
			}
			if (struct.isSetDscComentario()) {
				oprot.writeString(struct.dscComentario);
			}
			if (struct.isSetEnderecos()) {
				{
					oprot.writeI32(struct.enderecos.size());
					for (Endereco _iter76 : struct.enderecos) {
						_iter76.write(oprot);
					}
				}
			}
			if (struct.isSetFormacoes()) {
				{
					oprot.writeI32(struct.formacoes.size());
					for (Formacao _iter77 : struct.formacoes) {
						_iter77.write(oprot);
					}
				}
			}
			if (struct.isSetAtuacoes()) {
				{
					oprot.writeI32(struct.atuacoes.size());
					for (AtuacaoAtividade _iter78 : struct.atuacoes) {
						_iter78.write(oprot);
					}
				}
			}
			if (struct.isSetProducoes()) {
				{
					oprot.writeI32(struct.producoes.size());
					for (Producao _iter79 : struct.producoes) {
						_iter79.write(oprot);
					}
				}
			}
			if (struct.isSetNaturezaProjetos()) {
				{
					oprot.writeI32(struct.naturezaProjetos.size());
					for (NaturezaProjeto _iter80 : struct.naturezaProjetos) {
						_iter80.write(oprot);
					}
				}
			}
			if (struct.isSetPalavrasChave()) {
				{
					oprot.writeI32(struct.palavrasChave.size());
					for (PalavraChave _iter81 : struct.palavrasChave) {
						_iter81.write(oprot);
					}
				}
			}
			if (struct.isSetAreasAtuacao()) {
				{
					oprot.writeI32(struct.areasAtuacao.size());
					for (AreaAtuacao _iter82 : struct.areasAtuacao) {
						_iter82.write(oprot);
					}
				}
			}
		}

		@Override
		public void read(org.apache.thrift.protocol.TProtocol prot, Pessoa struct) throws org.apache.thrift.TException {
			TTupleProtocol iprot = (TTupleProtocol) prot;
			struct.nroIdCnpq = iprot.readString();
			struct.setNroIdCnpqIsSet(true);
			struct.nmeRh = iprot.readString();
			struct.setNmeRhIsSet(true);
			struct.dtaAtualizacaoCurriculo = iprot.readI64();
			struct.setDtaAtualizacaoCurriculoIsSet(true);
			BitSet incoming = iprot.readBitSet(10);
			if (incoming.get(0)) {
				struct.nmeCitacaoBibliog = iprot.readString();
				struct.setNmeCitacaoBibliogIsSet(true);
			}
			if (incoming.get(1)) {
				struct.tpoEnderCorr = iprot.readString();
				struct.setTpoEnderCorrIsSet(true);
			}
			if (incoming.get(2)) {
				struct.dscComentario = iprot.readString();
				struct.setDscComentarioIsSet(true);
			}
			if (incoming.get(3)) {
				{
					org.apache.thrift.protocol.TList _list83 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
					struct.enderecos = new ArrayList<Endereco>(_list83.size);
					Endereco _elem84;
					for (int _i85 = 0; _i85 < _list83.size; ++_i85) {
						_elem84 = new Endereco();
						_elem84.read(iprot);
						struct.enderecos.add(_elem84);
					}
				}
				struct.setEnderecosIsSet(true);
			}
			if (incoming.get(4)) {
				{
					org.apache.thrift.protocol.TList _list86 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
					struct.formacoes = new ArrayList<Formacao>(_list86.size);
					Formacao _elem87;
					for (int _i88 = 0; _i88 < _list86.size; ++_i88) {
						_elem87 = new Formacao();
						_elem87.read(iprot);
						struct.formacoes.add(_elem87);
					}
				}
				struct.setFormacoesIsSet(true);
			}
			if (incoming.get(5)) {
				{
					org.apache.thrift.protocol.TList _list89 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
					struct.atuacoes = new ArrayList<AtuacaoAtividade>(_list89.size);
					AtuacaoAtividade _elem90;
					for (int _i91 = 0; _i91 < _list89.size; ++_i91) {
						_elem90 = new AtuacaoAtividade();
						_elem90.read(iprot);
						struct.atuacoes.add(_elem90);
					}
				}
				struct.setAtuacoesIsSet(true);
			}
			if (incoming.get(6)) {
				{
					org.apache.thrift.protocol.TList _list92 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
					struct.producoes = new ArrayList<Producao>(_list92.size);
					Producao _elem93;
					for (int _i94 = 0; _i94 < _list92.size; ++_i94) {
						_elem93 = new Producao();
						_elem93.read(iprot);
						struct.producoes.add(_elem93);
					}
				}
				struct.setProducoesIsSet(true);
			}
			if (incoming.get(7)) {
				{
					org.apache.thrift.protocol.TList _list95 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
					struct.naturezaProjetos = new ArrayList<NaturezaProjeto>(_list95.size);
					NaturezaProjeto _elem96;
					for (int _i97 = 0; _i97 < _list95.size; ++_i97) {
						_elem96 = new NaturezaProjeto();
						_elem96.read(iprot);
						struct.naturezaProjetos.add(_elem96);
					}
				}
				struct.setNaturezaProjetosIsSet(true);
			}
			if (incoming.get(8)) {
				{
					org.apache.thrift.protocol.TList _list98 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
					struct.palavrasChave = new ArrayList<PalavraChave>(_list98.size);
					PalavraChave _elem99;
					for (int _i100 = 0; _i100 < _list98.size; ++_i100) {
						_elem99 = new PalavraChave();
						_elem99.read(iprot);
						struct.palavrasChave.add(_elem99);
					}
				}
				struct.setPalavrasChaveIsSet(true);
			}
			if (incoming.get(9)) {
				{
					org.apache.thrift.protocol.TList _list101 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
					struct.areasAtuacao = new ArrayList<AreaAtuacao>(_list101.size);
					AreaAtuacao _elem102;
					for (int _i103 = 0; _i103 < _list101.size; ++_i103) {
						_elem102 = new AreaAtuacao();
						_elem102.read(iprot);
						struct.areasAtuacao.add(_elem102);
					}
				}
				struct.setAreasAtuacaoIsSet(true);
			}
		}
	}

}
