/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package br.org.stela.intelectus.service.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-6-9")
public class ProducaoDimensional
		implements org.apache.thrift.TBase<ProducaoDimensional, ProducaoDimensional._Fields>, java.io.Serializable, Cloneable, Comparable<ProducaoDimensional> {
	private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ProducaoDimensional");

	private static final org.apache.thrift.protocol.TField PALAVRAS_CHAVE_FIELD_DESC =
			new org.apache.thrift.protocol.TField("palavrasChave", org.apache.thrift.protocol.TType.LIST, (short) 1);
	private static final org.apache.thrift.protocol.TField AUTORES_FIELD_DESC =
			new org.apache.thrift.protocol.TField("autores", org.apache.thrift.protocol.TType.LIST, (short) 2);
	private static final org.apache.thrift.protocol.TField PATENTES_FIELD_DESC =
			new org.apache.thrift.protocol.TField("patentes", org.apache.thrift.protocol.TType.LIST, (short) 3);
	private static final org.apache.thrift.protocol.TField CATEGORIAS_FIELD_DESC =
			new org.apache.thrift.protocol.TField("categorias", org.apache.thrift.protocol.TType.LIST, (short) 4);

	private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();

	static {
		schemes.put(StandardScheme.class, new ProducaoDimensionalStandardSchemeFactory());
		schemes.put(TupleScheme.class, new ProducaoDimensionalTupleSchemeFactory());
	}

	private List<br.org.stela.intelectus.lattes.thrift.PalavraChave> palavrasChave; // optional
	private List<br.org.stela.intelectus.lattes.thrift.ProducaoAutor> autores; // optional
	private List<br.org.stela.intelectus.lattes.thrift.ProducaoPatente> patentes; // optional
	private List<String> categorias; // optional

	/** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
	public enum _Fields implements org.apache.thrift.TFieldIdEnum {
		PALAVRAS_CHAVE((short) 1, "palavrasChave"),
		AUTORES((short) 2, "autores"),
		PATENTES((short) 3, "patentes"),
		CATEGORIAS((short) 4, "categorias");

		private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

		static {
			for (_Fields field : EnumSet.allOf(_Fields.class)) {
				byName.put(field.getFieldName(), field);
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, or null if its not found.
		 */
		public static _Fields findByThriftId(int fieldId) {
			switch (fieldId) {
			case 1: // PALAVRAS_CHAVE
				return PALAVRAS_CHAVE;
			case 2: // AUTORES
				return AUTORES;
			case 3: // PATENTES
				return PATENTES;
			case 4: // CATEGORIAS
				return CATEGORIAS;
			default:
				return null;
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, throwing an exception if it is not found.
		 */
		public static _Fields findByThriftIdOrThrow(int fieldId) {
			_Fields fields = findByThriftId(fieldId);
			if (fields == null)
				throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
			return fields;
		}

		/**
		 * Find the _Fields constant that matches name, or null if its not found.
		 */
		public static _Fields findByName(String name) {
			return byName.get(name);
		}

		private final short _thriftId;
		private final String _fieldName;

		_Fields(short thriftId, String fieldName) {
			_thriftId = thriftId;
			_fieldName = fieldName;
		}

		public short getThriftFieldId() {
			return _thriftId;
		}

		public String getFieldName() {
			return _fieldName;
		}
	}

	// isset id assignments
	private static final _Fields optionals[] = {_Fields.PALAVRAS_CHAVE, _Fields.AUTORES, _Fields.PATENTES, _Fields.CATEGORIAS};
	public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;

	static {
		Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
		tmpMap.put(_Fields.PALAVRAS_CHAVE,
				new org.apache.thrift.meta_data.FieldMetaData("palavrasChave", org.apache.thrift.TFieldRequirementType.OPTIONAL,
						new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, new org.apache.thrift.meta_data.StructMetaData(
								org.apache.thrift.protocol.TType.STRUCT, br.org.stela.intelectus.lattes.thrift.PalavraChave.class))));
		tmpMap.put(_Fields.AUTORES,
				new org.apache.thrift.meta_data.FieldMetaData("autores", org.apache.thrift.TFieldRequirementType.OPTIONAL,
						new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, new org.apache.thrift.meta_data.StructMetaData(
								org.apache.thrift.protocol.TType.STRUCT, br.org.stela.intelectus.lattes.thrift.ProducaoAutor.class))));
		tmpMap.put(_Fields.PATENTES,
				new org.apache.thrift.meta_data.FieldMetaData("patentes", org.apache.thrift.TFieldRequirementType.OPTIONAL,
						new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, new org.apache.thrift.meta_data.StructMetaData(
								org.apache.thrift.protocol.TType.STRUCT, br.org.stela.intelectus.lattes.thrift.ProducaoPatente.class))));
		tmpMap.put(_Fields.CATEGORIAS,
				new org.apache.thrift.meta_data.FieldMetaData("categorias", org.apache.thrift.TFieldRequirementType.OPTIONAL,
						new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
								new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
		metaDataMap = Collections.unmodifiableMap(tmpMap);
		org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ProducaoDimensional.class, metaDataMap);
	}

	public ProducaoDimensional() {
	}

	/**
	 * Performs a deep copy on <i>other</i>.
	 */
	public ProducaoDimensional(ProducaoDimensional other) {
		if (other.isSetPalavrasChave()) {
			List<br.org.stela.intelectus.lattes.thrift.PalavraChave> __this__palavrasChave =
					new ArrayList<br.org.stela.intelectus.lattes.thrift.PalavraChave>(other.palavrasChave.size());
			for (br.org.stela.intelectus.lattes.thrift.PalavraChave other_element : other.palavrasChave) {
				__this__palavrasChave.add(new br.org.stela.intelectus.lattes.thrift.PalavraChave(other_element));
			}
			this.palavrasChave = __this__palavrasChave;
		}
		if (other.isSetAutores()) {
			List<br.org.stela.intelectus.lattes.thrift.ProducaoAutor> __this__autores =
					new ArrayList<br.org.stela.intelectus.lattes.thrift.ProducaoAutor>(other.autores.size());
			for (br.org.stela.intelectus.lattes.thrift.ProducaoAutor other_element : other.autores) {
				__this__autores.add(new br.org.stela.intelectus.lattes.thrift.ProducaoAutor(other_element));
			}
			this.autores = __this__autores;
		}
		if (other.isSetPatentes()) {
			List<br.org.stela.intelectus.lattes.thrift.ProducaoPatente> __this__patentes =
					new ArrayList<br.org.stela.intelectus.lattes.thrift.ProducaoPatente>(other.patentes.size());
			for (br.org.stela.intelectus.lattes.thrift.ProducaoPatente other_element : other.patentes) {
				__this__patentes.add(new br.org.stela.intelectus.lattes.thrift.ProducaoPatente(other_element));
			}
			this.patentes = __this__patentes;
		}
		if (other.isSetCategorias()) {
			List<String> __this__categorias = new ArrayList<String>(other.categorias);
			this.categorias = __this__categorias;
		}
	}

	public ProducaoDimensional deepCopy() {
		return new ProducaoDimensional(this);
	}

	@Override
	public void clear() {
		this.palavrasChave = null;
		this.autores = null;
		this.patentes = null;
		this.categorias = null;
	}

	public int getPalavrasChaveSize() {
		return (this.palavrasChave == null) ? 0 : this.palavrasChave.size();
	}

	public java.util.Iterator<br.org.stela.intelectus.lattes.thrift.PalavraChave> getPalavrasChaveIterator() {
		return (this.palavrasChave == null) ? null : this.palavrasChave.iterator();
	}

	public void addToPalavrasChave(br.org.stela.intelectus.lattes.thrift.PalavraChave elem) {
		if (this.palavrasChave == null) {
			this.palavrasChave = new ArrayList<br.org.stela.intelectus.lattes.thrift.PalavraChave>();
		}
		this.palavrasChave.add(elem);
	}

	public List<br.org.stela.intelectus.lattes.thrift.PalavraChave> getPalavrasChave() {
		return this.palavrasChave;
	}

	public void setPalavrasChave(List<br.org.stela.intelectus.lattes.thrift.PalavraChave> palavrasChave) {
		this.palavrasChave = palavrasChave;
	}

	public void unsetPalavrasChave() {
		this.palavrasChave = null;
	}

	/** Returns true if field palavrasChave is set (has been assigned a value) and false otherwise */
	public boolean isSetPalavrasChave() {
		return this.palavrasChave != null;
	}

	public void setPalavrasChaveIsSet(boolean value) {
		if (!value) {
			this.palavrasChave = null;
		}
	}

	public int getAutoresSize() {
		return (this.autores == null) ? 0 : this.autores.size();
	}

	public java.util.Iterator<br.org.stela.intelectus.lattes.thrift.ProducaoAutor> getAutoresIterator() {
		return (this.autores == null) ? null : this.autores.iterator();
	}

	public void addToAutores(br.org.stela.intelectus.lattes.thrift.ProducaoAutor elem) {
		if (this.autores == null) {
			this.autores = new ArrayList<br.org.stela.intelectus.lattes.thrift.ProducaoAutor>();
		}
		this.autores.add(elem);
	}

	public List<br.org.stela.intelectus.lattes.thrift.ProducaoAutor> getAutores() {
		return this.autores;
	}

	public void setAutores(List<br.org.stela.intelectus.lattes.thrift.ProducaoAutor> autores) {
		this.autores = autores;
	}

	public void unsetAutores() {
		this.autores = null;
	}

	/** Returns true if field autores is set (has been assigned a value) and false otherwise */
	public boolean isSetAutores() {
		return this.autores != null;
	}

	public void setAutoresIsSet(boolean value) {
		if (!value) {
			this.autores = null;
		}
	}

	public int getPatentesSize() {
		return (this.patentes == null) ? 0 : this.patentes.size();
	}

	public java.util.Iterator<br.org.stela.intelectus.lattes.thrift.ProducaoPatente> getPatentesIterator() {
		return (this.patentes == null) ? null : this.patentes.iterator();
	}

	public void addToPatentes(br.org.stela.intelectus.lattes.thrift.ProducaoPatente elem) {
		if (this.patentes == null) {
			this.patentes = new ArrayList<br.org.stela.intelectus.lattes.thrift.ProducaoPatente>();
		}
		this.patentes.add(elem);
	}

	public List<br.org.stela.intelectus.lattes.thrift.ProducaoPatente> getPatentes() {
		return this.patentes;
	}

	public void setPatentes(List<br.org.stela.intelectus.lattes.thrift.ProducaoPatente> patentes) {
		this.patentes = patentes;
	}

	public void unsetPatentes() {
		this.patentes = null;
	}

	/** Returns true if field patentes is set (has been assigned a value) and false otherwise */
	public boolean isSetPatentes() {
		return this.patentes != null;
	}

	public void setPatentesIsSet(boolean value) {
		if (!value) {
			this.patentes = null;
		}
	}

	public int getCategoriasSize() {
		return (this.categorias == null) ? 0 : this.categorias.size();
	}

	public java.util.Iterator<String> getCategoriasIterator() {
		return (this.categorias == null) ? null : this.categorias.iterator();
	}

	public void addToCategorias(String elem) {
		if (this.categorias == null) {
			this.categorias = new ArrayList<String>();
		}
		this.categorias.add(elem);
	}

	public List<String> getCategorias() {
		return this.categorias;
	}

	public void setCategorias(List<String> categorias) {
		this.categorias = categorias;
	}

	public void unsetCategorias() {
		this.categorias = null;
	}

	/** Returns true if field categorias is set (has been assigned a value) and false otherwise */
	public boolean isSetCategorias() {
		return this.categorias != null;
	}

	public void setCategoriasIsSet(boolean value) {
		if (!value) {
			this.categorias = null;
		}
	}

	public void setFieldValue(_Fields field, Object value) {
		switch (field) {
		case PALAVRAS_CHAVE:
			if (value == null) {
				unsetPalavrasChave();
			} else {
				setPalavrasChave((List<br.org.stela.intelectus.lattes.thrift.PalavraChave>) value);
			}
			break;

		case AUTORES:
			if (value == null) {
				unsetAutores();
			} else {
				setAutores((List<br.org.stela.intelectus.lattes.thrift.ProducaoAutor>) value);
			}
			break;

		case PATENTES:
			if (value == null) {
				unsetPatentes();
			} else {
				setPatentes((List<br.org.stela.intelectus.lattes.thrift.ProducaoPatente>) value);
			}
			break;

		case CATEGORIAS:
			if (value == null) {
				unsetCategorias();
			} else {
				setCategorias((List<String>) value);
			}
			break;

		}
	}

	public Object getFieldValue(_Fields field) {
		switch (field) {
		case PALAVRAS_CHAVE:
			return getPalavrasChave();

		case AUTORES:
			return getAutores();

		case PATENTES:
			return getPatentes();

		case CATEGORIAS:
			return getCategorias();

		}
		throw new IllegalStateException();
	}

	/** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
	public boolean isSet(_Fields field) {
		if (field == null) {
			throw new IllegalArgumentException();
		}

		switch (field) {
		case PALAVRAS_CHAVE:
			return isSetPalavrasChave();
		case AUTORES:
			return isSetAutores();
		case PATENTES:
			return isSetPatentes();
		case CATEGORIAS:
			return isSetCategorias();
		}
		throw new IllegalStateException();
	}

	@Override
	public boolean equals(Object that) {
		if (that == null)
			return false;
		if (that instanceof ProducaoDimensional)
			return this.equals((ProducaoDimensional) that);
		return false;
	}

	public boolean equals(ProducaoDimensional that) {
		if (that == null)
			return false;

		boolean this_present_palavrasChave = true && this.isSetPalavrasChave();
		boolean that_present_palavrasChave = true && that.isSetPalavrasChave();
		if (this_present_palavrasChave || that_present_palavrasChave) {
			if (!(this_present_palavrasChave && that_present_palavrasChave))
				return false;
			if (!this.palavrasChave.equals(that.palavrasChave))
				return false;
		}

		boolean this_present_autores = true && this.isSetAutores();
		boolean that_present_autores = true && that.isSetAutores();
		if (this_present_autores || that_present_autores) {
			if (!(this_present_autores && that_present_autores))
				return false;
			if (!this.autores.equals(that.autores))
				return false;
		}

		boolean this_present_patentes = true && this.isSetPatentes();
		boolean that_present_patentes = true && that.isSetPatentes();
		if (this_present_patentes || that_present_patentes) {
			if (!(this_present_patentes && that_present_patentes))
				return false;
			if (!this.patentes.equals(that.patentes))
				return false;
		}

		boolean this_present_categorias = true && this.isSetCategorias();
		boolean that_present_categorias = true && that.isSetCategorias();
		if (this_present_categorias || that_present_categorias) {
			if (!(this_present_categorias && that_present_categorias))
				return false;
			if (!this.categorias.equals(that.categorias))
				return false;
		}

		return true;
	}

	@Override
	public int hashCode() {
		List<Object> list = new ArrayList<Object>();

		boolean present_palavrasChave = true && (isSetPalavrasChave());
		list.add(present_palavrasChave);
		if (present_palavrasChave)
			list.add(palavrasChave);

		boolean present_autores = true && (isSetAutores());
		list.add(present_autores);
		if (present_autores)
			list.add(autores);

		boolean present_patentes = true && (isSetPatentes());
		list.add(present_patentes);
		if (present_patentes)
			list.add(patentes);

		boolean present_categorias = true && (isSetCategorias());
		list.add(present_categorias);
		if (present_categorias)
			list.add(categorias);

		return list.hashCode();
	}

	@Override
	public int compareTo(ProducaoDimensional other) {
		if (!getClass().equals(other.getClass())) {
			return getClass().getName().compareTo(other.getClass().getName());
		}

		int lastComparison = 0;

		lastComparison = Boolean.valueOf(isSetPalavrasChave()).compareTo(other.isSetPalavrasChave());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetPalavrasChave()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.palavrasChave, other.palavrasChave);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetAutores()).compareTo(other.isSetAutores());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetAutores()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.autores, other.autores);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetPatentes()).compareTo(other.isSetPatentes());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetPatentes()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.patentes, other.patentes);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetCategorias()).compareTo(other.isSetCategorias());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetCategorias()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.categorias, other.categorias);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		return 0;
	}

	public _Fields fieldForId(int fieldId) {
		return _Fields.findByThriftId(fieldId);
	}

	public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
		schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
	}

	public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
		schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("ProducaoDimensional(");
		boolean first = true;

		if (isSetPalavrasChave()) {
			sb.append("palavrasChave:");
			if (this.palavrasChave == null) {
				sb.append("null");
			} else {
				sb.append(this.palavrasChave);
			}
			first = false;
		}
		if (isSetAutores()) {
			if (!first)
				sb.append(", ");
			sb.append("autores:");
			if (this.autores == null) {
				sb.append("null");
			} else {
				sb.append(this.autores);
			}
			first = false;
		}
		if (isSetPatentes()) {
			if (!first)
				sb.append(", ");
			sb.append("patentes:");
			if (this.patentes == null) {
				sb.append("null");
			} else {
				sb.append(this.patentes);
			}
			first = false;
		}
		if (isSetCategorias()) {
			if (!first)
				sb.append(", ");
			sb.append("categorias:");
			if (this.categorias == null) {
				sb.append("null");
			} else {
				sb.append(this.categorias);
			}
			first = false;
		}
		sb.append(")");
		return sb.toString();
	}

	public void validate() throws org.apache.thrift.TException {
		// check for required fields
		// check for sub-struct validity
	}

	private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
		try {
			write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
		} catch (org.apache.thrift.TException te) {
			throw new java.io.IOException(te);
		}
	}

	private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
		try {
			read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
		} catch (org.apache.thrift.TException te) {
			throw new java.io.IOException(te);
		}
	}

	private static class ProducaoDimensionalStandardSchemeFactory implements SchemeFactory {
		public ProducaoDimensionalStandardScheme getScheme() {
			return new ProducaoDimensionalStandardScheme();
		}
	}

	private static class ProducaoDimensionalStandardScheme extends StandardScheme<ProducaoDimensional> {

		public void read(org.apache.thrift.protocol.TProtocol iprot, ProducaoDimensional struct) throws org.apache.thrift.TException {
			org.apache.thrift.protocol.TField schemeField;
			iprot.readStructBegin();
			while (true) {
				schemeField = iprot.readFieldBegin();
				if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
					break;
				}
				switch (schemeField.id) {
				case 1: // PALAVRAS_CHAVE
					if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
						{
							org.apache.thrift.protocol.TList _list62 = iprot.readListBegin();
							struct.palavrasChave = new ArrayList<br.org.stela.intelectus.lattes.thrift.PalavraChave>(_list62.size);
							br.org.stela.intelectus.lattes.thrift.PalavraChave _elem63;
							for (int _i64 = 0; _i64 < _list62.size; ++_i64) {
								_elem63 = new br.org.stela.intelectus.lattes.thrift.PalavraChave();
								_elem63.read(iprot);
								struct.palavrasChave.add(_elem63);
							}
							iprot.readListEnd();
						}
						struct.setPalavrasChaveIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 2: // AUTORES
					if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
						{
							org.apache.thrift.protocol.TList _list65 = iprot.readListBegin();
							struct.autores = new ArrayList<br.org.stela.intelectus.lattes.thrift.ProducaoAutor>(_list65.size);
							br.org.stela.intelectus.lattes.thrift.ProducaoAutor _elem66;
							for (int _i67 = 0; _i67 < _list65.size; ++_i67) {
								_elem66 = new br.org.stela.intelectus.lattes.thrift.ProducaoAutor();
								_elem66.read(iprot);
								struct.autores.add(_elem66);
							}
							iprot.readListEnd();
						}
						struct.setAutoresIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 3: // PATENTES
					if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
						{
							org.apache.thrift.protocol.TList _list68 = iprot.readListBegin();
							struct.patentes = new ArrayList<br.org.stela.intelectus.lattes.thrift.ProducaoPatente>(_list68.size);
							br.org.stela.intelectus.lattes.thrift.ProducaoPatente _elem69;
							for (int _i70 = 0; _i70 < _list68.size; ++_i70) {
								_elem69 = new br.org.stela.intelectus.lattes.thrift.ProducaoPatente();
								_elem69.read(iprot);
								struct.patentes.add(_elem69);
							}
							iprot.readListEnd();
						}
						struct.setPatentesIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 4: // CATEGORIAS
					if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
						{
							org.apache.thrift.protocol.TList _list71 = iprot.readListBegin();
							struct.categorias = new ArrayList<String>(_list71.size);
							String _elem72;
							for (int _i73 = 0; _i73 < _list71.size; ++_i73) {
								_elem72 = iprot.readString();
								struct.categorias.add(_elem72);
							}
							iprot.readListEnd();
						}
						struct.setCategoriasIsSet(true);
					} else {
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				default:
					org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
				}
				iprot.readFieldEnd();
			}
			iprot.readStructEnd();
			struct.validate();
		}

		public void write(org.apache.thrift.protocol.TProtocol oprot, ProducaoDimensional struct) throws org.apache.thrift.TException {
			struct.validate();

			oprot.writeStructBegin(STRUCT_DESC);
			if (struct.palavrasChave != null) {
				if (struct.isSetPalavrasChave()) {
					oprot.writeFieldBegin(PALAVRAS_CHAVE_FIELD_DESC);
					{
						oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.palavrasChave.size()));
						for (br.org.stela.intelectus.lattes.thrift.PalavraChave _iter74 : struct.palavrasChave) {
							_iter74.write(oprot);
						}
						oprot.writeListEnd();
					}
					oprot.writeFieldEnd();
				}
			}
			if (struct.autores != null) {
				if (struct.isSetAutores()) {
					oprot.writeFieldBegin(AUTORES_FIELD_DESC);
					{
						oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.autores.size()));
						for (br.org.stela.intelectus.lattes.thrift.ProducaoAutor _iter75 : struct.autores) {
							_iter75.write(oprot);
						}
						oprot.writeListEnd();
					}
					oprot.writeFieldEnd();
				}
			}
			if (struct.patentes != null) {
				if (struct.isSetPatentes()) {
					oprot.writeFieldBegin(PATENTES_FIELD_DESC);
					{
						oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.patentes.size()));
						for (br.org.stela.intelectus.lattes.thrift.ProducaoPatente _iter76 : struct.patentes) {
							_iter76.write(oprot);
						}
						oprot.writeListEnd();
					}
					oprot.writeFieldEnd();
				}
			}
			if (struct.categorias != null) {
				if (struct.isSetCategorias()) {
					oprot.writeFieldBegin(CATEGORIAS_FIELD_DESC);
					{
						oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.categorias.size()));
						for (String _iter77 : struct.categorias) {
							oprot.writeString(_iter77);
						}
						oprot.writeListEnd();
					}
					oprot.writeFieldEnd();
				}
			}
			oprot.writeFieldStop();
			oprot.writeStructEnd();
		}

	}

	private static class ProducaoDimensionalTupleSchemeFactory implements SchemeFactory {
		public ProducaoDimensionalTupleScheme getScheme() {
			return new ProducaoDimensionalTupleScheme();
		}
	}

	private static class ProducaoDimensionalTupleScheme extends TupleScheme<ProducaoDimensional> {

		@Override
		public void write(org.apache.thrift.protocol.TProtocol prot, ProducaoDimensional struct) throws org.apache.thrift.TException {
			TTupleProtocol oprot = (TTupleProtocol) prot;
			BitSet optionals = new BitSet();
			if (struct.isSetPalavrasChave()) {
				optionals.set(0);
			}
			if (struct.isSetAutores()) {
				optionals.set(1);
			}
			if (struct.isSetPatentes()) {
				optionals.set(2);
			}
			if (struct.isSetCategorias()) {
				optionals.set(3);
			}
			oprot.writeBitSet(optionals, 4);
			if (struct.isSetPalavrasChave()) {
				{
					oprot.writeI32(struct.palavrasChave.size());
					for (br.org.stela.intelectus.lattes.thrift.PalavraChave _iter78 : struct.palavrasChave) {
						_iter78.write(oprot);
					}
				}
			}
			if (struct.isSetAutores()) {
				{
					oprot.writeI32(struct.autores.size());
					for (br.org.stela.intelectus.lattes.thrift.ProducaoAutor _iter79 : struct.autores) {
						_iter79.write(oprot);
					}
				}
			}
			if (struct.isSetPatentes()) {
				{
					oprot.writeI32(struct.patentes.size());
					for (br.org.stela.intelectus.lattes.thrift.ProducaoPatente _iter80 : struct.patentes) {
						_iter80.write(oprot);
					}
				}
			}
			if (struct.isSetCategorias()) {
				{
					oprot.writeI32(struct.categorias.size());
					for (String _iter81 : struct.categorias) {
						oprot.writeString(_iter81);
					}
				}
			}
		}

		@Override
		public void read(org.apache.thrift.protocol.TProtocol prot, ProducaoDimensional struct) throws org.apache.thrift.TException {
			TTupleProtocol iprot = (TTupleProtocol) prot;
			BitSet incoming = iprot.readBitSet(4);
			if (incoming.get(0)) {
				{
					org.apache.thrift.protocol.TList _list82 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
					struct.palavrasChave = new ArrayList<br.org.stela.intelectus.lattes.thrift.PalavraChave>(_list82.size);
					br.org.stela.intelectus.lattes.thrift.PalavraChave _elem83;
					for (int _i84 = 0; _i84 < _list82.size; ++_i84) {
						_elem83 = new br.org.stela.intelectus.lattes.thrift.PalavraChave();
						_elem83.read(iprot);
						struct.palavrasChave.add(_elem83);
					}
				}
				struct.setPalavrasChaveIsSet(true);
			}
			if (incoming.get(1)) {
				{
					org.apache.thrift.protocol.TList _list85 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
					struct.autores = new ArrayList<br.org.stela.intelectus.lattes.thrift.ProducaoAutor>(_list85.size);
					br.org.stela.intelectus.lattes.thrift.ProducaoAutor _elem86;
					for (int _i87 = 0; _i87 < _list85.size; ++_i87) {
						_elem86 = new br.org.stela.intelectus.lattes.thrift.ProducaoAutor();
						_elem86.read(iprot);
						struct.autores.add(_elem86);
					}
				}
				struct.setAutoresIsSet(true);
			}
			if (incoming.get(2)) {
				{
					org.apache.thrift.protocol.TList _list88 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
					struct.patentes = new ArrayList<br.org.stela.intelectus.lattes.thrift.ProducaoPatente>(_list88.size);
					br.org.stela.intelectus.lattes.thrift.ProducaoPatente _elem89;
					for (int _i90 = 0; _i90 < _list88.size; ++_i90) {
						_elem89 = new br.org.stela.intelectus.lattes.thrift.ProducaoPatente();
						_elem89.read(iprot);
						struct.patentes.add(_elem89);
					}
				}
				struct.setPatentesIsSet(true);
			}
			if (incoming.get(3)) {
				{
					org.apache.thrift.protocol.TList _list91 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
					struct.categorias = new ArrayList<String>(_list91.size);
					String _elem92;
					for (int _i93 = 0; _i93 < _list91.size; ++_i93) {
						_elem92 = iprot.readString();
						struct.categorias.add(_elem92);
					}
				}
				struct.setCategoriasIsSet(true);
			}
		}
	}

}
